version: "3.5"
services:
  db:
    build:
      context: postgres
    container_name: sabu_db
    image: sabu_db:v0.1
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - "/sabu/server/.env"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
  redis:
    image: redis:alpine3.18
    restart: always
    container_name: sabu_redis
    ports:
      - "127.0.0.1:6379:6379"